// Module plan for splitting the de-minified bundle into ES modules.
// Each entry: { file, range: 'firstUnit..lastUnit' } — ranges are inclusive and
// resolved on the ordered unit list (docs/research/units.txt). Rollup emitted the
// original source modules contiguously, so consecutive units belong together.
// `drop` lists unit ids that are dead code in the bundle (never emitted).

export const dropUnits = [
  74,  // new URLSearchParams(window.location.search);   (dead)
  77,  // new Vector3(0,0,0), new Vector3(0,0,0), ...     (dead)
];

export const plan = [
  // ---------------- core ----------------
  { file: 'src/webgl/loaders/ktx-texture-loader.js', range: 'Ra..fO' },
  { file: 'src/core/events.js', range: 'Mt..te' },
  { file: 'src/config/debug.js', range: 'JO..ZO' },
  { file: 'src/config/breakpoints.js', range: 'co..co' },
  { file: 'src/config/media-paths.js', range: '$O..cF' },
  { file: 'src/config/sounds-manifest.js', range: 'uF..pF' },
  { file: 'src/config/screen.js', range: 'Zb..AF' },
  { file: 'src/config/webp-textures-manifest.js', range: 'gF..xF' },
  { file: 'src/config/ktx-textures-manifest.js', range: 'EF..BF' },
  { file: 'src/config/assets-manifest.js', range: 'DF..Po' },
  { file: 'src/core/loaders/AssetsLoader.js', range: 'Aa..Aa' },
  { file: 'src/core/loaders/BlobImageLoader.js', range: 'Lh..NF+1' },        // FileLoader(blob) → ImageLoader
  { file: 'src/core/loaders/JsonLoader.js', range: 'Ph..kF+1' },
  { file: 'src/core/loaders/BlobTextureLoader.js', range: 'Oh..UF+2' },      // + Cache.enabled = true
  { file: 'src/core/AssetsManager.js', range: 'Rs..GF+1' },
  { file: 'src/core/Ticker.js', range: 'fc..HF+1' },
  { file: 'src/core/create-core.js', range: 'QF..QF' },
  // ---------------- ui utils ----------------
  { file: 'src/utils/math.js', range: 'I3..EE' },
  { file: 'src/utils/dom.js', range: 'or..or' },
  { file: 'src/utils/device.js', range: 'gn..ti' },
  { file: 'src/components/CursorIndication.js', range: 'R3..SM' },
  { file: 'src/utils/bee-text-format.js', range: 'U3..Y3' },
  { file: 'src/components/BeeTextIndication.js', range: 'X3..j3' },
  { file: 'src/composables/useOrientation.js', range: 'K3..J3' },
  { file: 'src/components/OrientationIndication.js', range: 'Z3..iG' },
  { file: 'src/components/MainButton.js', range: 'sG..Sh' },
  { file: 'src/components/MenuButton.js', range: 'yG..EG' },
  { file: 'src/components/NavLabButton.js', range: 'SG..TG' },
  { file: 'src/utils/map-range.js', range: 'qh..qh' },
  { file: 'src/components/SoundButton.js', range: 'CG..ME' },
  { file: 'src/utils/clamp.js', range: 'Kr..ei' },
  { file: 'src/utils/will-change.js', range: 'dp..Wn' },
  { file: 'src/components/TextComponent.js', range: 'kG..xn' },
  { file: 'src/components/GridWrapper.js', range: 'UG..Qn' },
  { file: 'src/config/navbar.js', range: 'QH..GM' },
  { file: 'src/composables/useAboutNavbarTheme.js', range: 'zH..zH' },
  { file: 'src/data/about.js', range: 'VH..Ll' },
  { file: 'src/data/global.js', range: 'KH..Ui' },
  { file: 'src/composables/useLenisScroll.js', range: 'nQ..r0' },
  { file: 'src/composables/useMediaAutoplay.js', range: 'iQ..aQ' },
  { file: 'src/components/MediaComponent.js', range: 'lQ..lA' },
  { file: 'src/components/ParallaxWrapperComponent.js', range: 'fQ..zM' },
  { file: 'src/components/WebglBgComponent.js', range: 'pQ..zs' },
  { file: 'src/composables/useTextReveal.js', range: 'o0..AQ' },
  { file: 'src/components/about/ContentBlock.js', range: 'gQ..IQ' },
  { file: 'src/components/about/FlowersBlock.js', range: 'RQ..YQ' },
  { file: 'src/components/BeeBlock.js', range: 'XQ..cA' },
  { file: 'src/components/about/HeroBlock.js', range: '$Q..iz' },
  { file: 'src/components/about/IntroBlock.js', range: 'sz..hz' },
  { file: 'src/components/icons/CrossIcon.js', range: 'dz..VM' },
  { file: 'src/utils/browser.js', range: 'a0..a0' },
  { file: 'src/components/FooterBlock.js', range: 'Az..l0' },
  { file: 'src/components/HeaderBlock.js', range: 'Pz..WM' },
  { file: 'src/components/about/CardBlock.js', range: 'Oz..Zz' },
  { file: 'src/components/WebglSectionBlock.js', range: '$z..YM' },
  { file: 'src/views/AboutView.js', range: 'oV..aV' },
  { file: 'src/composables/useHomeNavbarTheme.js', range: 'lV..lV' },
  { file: 'src/data/home.js', range: 'Og..Hw+1' },            // + for-of poster fixup statement
  { file: 'src/components/ArrowButton.js', range: 'cV..C_' },
  { file: 'src/utils/throttle.js', range: 'XM..XM' },
  { file: 'src/components/ArchivesBlock.js', range: 'fV..BV' },
  { file: 'src/components/AgencyLink.js', range: 'DV..rS' },
  { file: 'src/components/home/HeroBlock.js', range: 'GV..XV' },
  { file: 'src/components/home/IntroBlock.js', range: 'qV..ZV' },
  { file: 'src/config/slider.js', range: '$V..Uo' },
  { file: 'src/components/ProjectBlock.js', range: 'i4..oS' },
  { file: 'src/views/HomeView.js', range: 'E4..b4' },
  { file: 'src/data/playground.js', range: 'T4..M_' },
  { file: 'src/webgl/bee/playground-bee-layout.js', range: 'bh..mW' },
  { file: 'src/components/playground/ContentBlock.js', range: '_W..SW' },
  { file: 'src/config/hero-transitions.js', range: 'D_..wW' },
  { file: 'src/components/playground/HeroBlock.js', range: 'bW..CW' },
  { file: 'src/views/PlaygroundView.js', range: 'MW..RW' },
  { file: 'src/router/index.js', range: 'Pf..Wu+1' },          // + beforeEach statement
  { file: 'src/components/NavbarComponent.js', range: 'LW..zW' },
  { file: 'src/composables/useSeo.js', range: 'VW..t5' },
  { file: 'src/components/LoaderBlock.js', range: 'n5..h5' },
  { file: 'src/components/VideoPlayer.js', range: 'd5..C5' },
  { file: 'src/AppRoot.js', range: 'M5..P5' },
  // ---------------- app / webgl ----------------
  { file: 'src/core/URLParams.js', range: 'o8..a8' },
  { file: 'src/core/SoundController.js', range: 'Ds..l8+1' },
  { file: 'src/core/tools/Mouse.js', range: 'Ua..c8' },
  { file: 'src/core/tools/Viewport.js', range: 'Fp..u8+1' },
  { file: 'src/core/tools/index.js', range: 'h8..h8' },
  { file: 'src/webgl/postprocessing/fullscreen.js', range: 'f8..x0+2' },
  { file: 'src/webgl/shared-uniforms.js', range: 'gA..Yl' },
  { file: 'src/webgl/utils/shader-chunk.js', range: '_8..bn' },
  { file: 'src/webgl/postprocessing/NoiseMaterial.js', range: 'v8..E8' },
  { file: 'src/webgl/postprocessing/VelocityBlendShader.js', range: 'S8..b8' },
  { file: 'src/webgl/postprocessing/FinalShader.js', range: 'T8..M8' },
  { file: 'src/webgl/postprocessing/LayerRenderPass.js', range: 'I8..I8' },
  { file: 'src/webgl/Renderer.js', range: 'kS..kS' },
  { file: 'src/webgl/cameras/ScrollCamera.js', range: 'R8..R8' },
  { file: 'src/webgl/materials/ColorMaterial.js', range: 'B8..O8' },
  { file: 'src/webgl/materials/MediaMaterial.js', range: 'F8..G8' },
  { file: 'src/webgl/scenes/MainScene.js', range: 'H8..rY' },
  { file: 'src/webgl/cameras/MainCamera.js', range: 'oY..oY' },
  { file: 'src/webgl/materials/EnvTextureMaterial.js', range: 'aY..FI' },
  { file: 'src/webgl/materials/LeavesMaterial.js', range: 'hY..AY' },
  { file: 'src/webgl/materials/TextureMaterial.js', range: 'gY..yY' },
  { file: 'src/webgl/materials/GradientMaterial.js', range: 'xY..bY' },
  { file: 'src/webgl/objects/GradientSphere.js', range: 'NI..NI' },
  { file: 'src/webgl/materials/CloudsMaterial.js', range: 'TY..RY' },
  { file: 'src/webgl/utils/texture-settings.js', range: 'kI..WI' },
  { file: 'src/webgl/objects/Clouds.js', range: 'YI..YI' },
  { file: 'src/webgl/objects/Particles.js', range: 'LY..LY' },
  { file: 'src/webgl/materials/WaterMaterial.js', range: 'PY..kY' },
  { file: 'src/webgl/objects/Water.js', range: 'UY..UY' },
  { file: 'src/webgl/utils/hash-blur.js', range: 'w0..ZI' },
  { file: 'src/webgl/environments/AboutEnvironment.js', range: 'zY..WY' },
  { file: 'src/webgl/materials/ParticlesMaterial.js', range: 'YY..JY' },
  { file: 'src/webgl/objects/ParticlesSimple.js', range: 'ZY..$Y' },
  { file: 'src/webgl/environments/HomeEnvironment.js', range: 'XS..nX' },
  { file: 'src/webgl/scenes/EnvScene.js', range: 'iX..iX' },
  { file: 'src/webgl/cameras/EnvCamera.js', range: 'sX..sX' },
  { file: 'src/webgl/cameras/CameraRig.js', range: 'rX..rX' },
  { file: 'src/webgl/cameras/OrthoCamera.js', range: 'oX..oX' },
  { file: 'src/webgl/cameras/TopCamera.js', range: 'aX..aX' },
  { file: 'src/webgl/materials/page-transition.js', range: 'CX..kX' },
  { file: 'src/webgl/objects/Fruits.js', range: 'Cw..Cw' },
  { file: 'src/webgl/bee/bee-texts.js', range: 'C0..XX' },
  { file: 'src/webgl/bee/bee-projection.js', range: 'Bw..e6' },
  { file: 'src/webgl/objects/Bee.js', range: 'Dw..l6' },
  { file: 'src/webgl/materials/LoaderMaterial.js', range: 'c6..f6' },
  { file: 'src/webgl/objects/LoaderPlane.js', range: 'p6..p6' },
  { file: 'src/webgl/materials/FlowerBackgroundMaterial.js', range: 'A6..v6' },
  { file: 'src/webgl/objects/FlowerGroup.js', range: 'Fw..x6' },
  { file: 'src/webgl/scenes/TopScene.js', range: 'Nw..E6' },
  { file: 'src/webgl/fluid/Mouse.js', range: 'S6..dc' },
  { file: 'src/webgl/fluid/ShaderPass.js', range: 'Qc..Qc' },
  { file: 'src/webgl/fluid/Advection.js', range: 'kw..b6' },
  { file: 'src/webgl/fluid/Divergence.js', range: 'T6..C6' },
  { file: 'src/webgl/fluid/ExternalForce.js', range: 'M6..R6' },
  { file: 'src/webgl/fluid/Poisson.js', range: 'B6..D6' },
  { file: 'src/webgl/fluid/Pressure.js', range: 'L6..P6' },
  { file: 'src/webgl/fluid/Viscous.js', range: 'O6..F6' },
  { file: 'src/webgl/fluid/Simulation.js', range: 'N6..G6' },
  { file: 'src/webgl/WebGL.js', range: 'H6..Q6' },
  { file: 'src/core/App.js', range: 'Pa..I' },
  { file: 'src/utils/prevent-zoom.js', range: 'J6..J6+1' },
  { file: 'src/utils/manifest-link.js', range: 'Z6..Z6+1' },
  { file: 'src/main.js', range: 'Z6+2..END' },
];

// Readable names for the app's own (minified) top-level identifiers.
export const renames = {
  // core
  Ra: 'ktx2Loader', Cd: 'ktx2LoaderReady', dO: 'initKtxTextureLoader', fO: 'KtxTextureLoader',
  Mt: 'eventId', ce: 'EVENTS', pO: 'EVENT_HANDLER_NAMES', La: 'Emitter', Qm: 'EmitterClass', te: 'emitter',
  JO: 'IS_DEBUG', ZO: 'CHECK_SHADER_ERRORS', co: 'BREAKPOINTS',
  $O: 'PROJECT_MEDIA_COUNTS', jb: 'IMAGE_RE', Kb: 'MP4_RE', Yf: 'ARCHIVES_BASE_DIR', ah: 'ARCHIVES_COMPRESSED_DIR',
  gx: 'SHOWREEL_BASE_DIR', eF: 'SHOWREEL_COMPRESSED_DIR', tF: 'swapDir', nF: 'toCompressedArchiveVideo',
  iF: 'toArchivePoster', sF: 'deviceBucket', Jb: 'toCompressedShowreel', rF: 'toCompressedArchiveImage',
  oF: 'projectImageSize', aF: 'toWebpMedia', lF: 'toProjectWebp', cF: 'buildProjectMediaUrls',
  uF: 'SOUNDS_DIR', hF: 'SOUNDS_EXT', dF: 'SOUNDS', fF: 'soundPath', pF: 'buildSoundsManifest',
  Zb: 'LARGE_DESKTOP_MIN', $b: 'LARGE_DESKTOP_QUERY', AF: 'isLargeDesktop',
  gF: 'WEBP_TEXTURES', mF: 'stripExt', _F: 'isMobileTextureWidth', vF: 'webpTexturePath', yF: 'webpParentDir',
  ag: 'resolveWebpTexture', xF: 'buildWebpTexturesManifest',
  EF: 'SCENE_KTX_DIR', Xf: 'SCENE_TEXTURES', SF: 'PROJECT_TEXTURE_COUNTS', wF: 'KTX_TEXTURES', bF: 'stripExtension',
  TF: 'sceneTextureSize', mx: 'sceneTextureSizeFor', CF: 'isMobileKtxWidth', eT: 'projectTextureSize',
  _x: 'sceneTexturePath', MF: 'ktxTexturePath', IF: 'projectTexturePath', RF: 'ktxParentDir', lg: 'resolveKtxTexture',
  Tl: 'textureEntry', BF: 'buildKtxTexturesManifest',
  DF: 'WEBP_TEXTURE_KEYS', LF: 'CLOUD_TEXTURE_KEYS', PF: 'BASE_URL', Zs: 'withBase', OF: 'assetUrl',
  ur: 'ktxTextures', vx: 'webpTextures', FF: 'sounds', Wm: 'usedWebpTextures', Sa: 'cloudTextures', tT: 'mountainTexture',
  Cl: 'projectMediaUrls', wa: 'assetPaths', Po: 'ASSETS_MANIFEST',
  Aa: 'AssetsLoader', NF: 'BlobImageLoader', kF: 'JsonLoader', UF: 'BlobTextureLoader', GF: 'AssetsManager', HF: 'Ticker',
  QF: 'createCore',
  // ui utils
  I3: 'DEG2RAD', Wi: 'lerp', xE: 'degToRad', y_: 'remToPx', EE: 'remToPxMap', or: 'getOffset', gn: 'isTabletWidth', ti: 'isTouch',
  qh: 'mapRange', Kr: 'clamp', ei: 'mapRangeClamped', dp: 'setWillChange', fp: 'willChangeDuringTween', Wn: 'GSAP_DEFAULTS',
  GM: 'isCompactNavbar', QH: 'COMPACT_NAVBAR_MAX_WIDTH', zH: 'useAboutNavbarTheme', lV: 'useHomeNavbarTheme',
  K3: 'isLandscape', wM: 'isIPadLike', bM: 'isTabletDevice', wE: 'isTabletLandscape', J3: 'useOrientation',
  a0: 'isSafari', XM: 'throttle',
  nQ: 'SCROLL_VISIBILITY_MARGIN', Lf: 'scrollListeners', Nd: 'lenisScrollBound', JE: 'onLenisScroll', HM: 'getScrollY',
  QM: 'isRectNearViewport', r0: 'onScroll',
  iQ: 'AUTOPLAY_OBSERVER_OPTIONS', Ap: 'autoplayEntries', gp: 'autoplaySuspended', aA: 'autoplayPaused', sQ: 'applyAutoplay',
  rQ: 'suspendMediaAutoplay', oQ: 'resumeMediaAutoplay', aQ: 'useMediaAutoplay',
  o0: 'isTouchTablet', ZE: 'scaleStagger', AQ: 'useTextReveal',
  U3: 'PROPER_NOUNS', G3: 'CONTRACTIONS', H3: 'escapeRegExp', Q3: 'isAllCaps', z3: 'collectProperNouns', V3: 'capitalizeSentences',
  W3: 'restoreProperNouns', Y3: 'formatBeeText',
  // data
  VH: 'aboutHeader', WH: 'aboutHero', YH: 'aboutIntro', XH: 'aboutFlowers', qH: 'aboutCards', jH: 'aboutContent', Ll: 'aboutData',
  KH: 'SITE_TITLE', JH: 'SITE_INFOS', ZH: 'navbarData', $H: 'loaderData', eQ: 'orientationData', tQ: 'footerData', Ui: 'globalData',
  Og: 'DNA_PLACEHOLDER_IMAGE', Da: 'homeData', T4: 'playgroundHero', C4: 'playgroundContent', M4: 'playgroundContentBee', M_: 'playgroundData',
  $V: 'SLIDER_GAP_DESKTOP', e4: 'SLIDER_GAP_MOBILE', mp: 'sliderGap', t4: 'SLIDER_OPTIONS_DESKTOP', n4: 'SLIDER_OPTIONS_MOBILE', Uo: 'sliderOptions',
  D_: 'HERO_TRANSITIONS', wW: 'nonZero',
  // components (inner sfc object → *Component, exported wrapper → name)
  k3: 'CursorIndicationSfc', SM: 'CursorIndication', q3: 'BeeTextIndicationSfc', j3: 'BeeTextIndication',
  nG: 'OrientationIndicationSfc', iG: 'OrientationIndication', rG: 'MainButtonSfc', Sh: 'MainButton',
  xG: 'MenuButtonSfc', EG: 'MenuButton', bG: 'NavLabButtonSfc', TG: 'NavLabButton', IG: 'SoundButtonSfc', ME: 'SoundButton',
  kG: 'TextComponentSfc', xn: 'TextComponent', UG: 'GridWrapperSfc', Qn: 'GridWrapper',
  dQ: 'MediaComponentSfc', lA: 'MediaComponent', fQ: 'ParallaxWrapperSfc', zM: 'ParallaxWrapperComponent',
  pQ: 'WebglBgSfc', zs: 'WebglBgComponent', MQ: 'AboutContentBlockSfc', IQ: 'AboutContentBlock',
  WQ: 'FlowersBlockSfc', YQ: 'FlowersBlock', ZQ: 'BeeBlockSfc', cA: 'BeeBlock', nz: 'AboutHeroBlockSfc', iz: 'AboutHeroBlock',
  uz: 'AboutIntroBlockSfc', hz: 'AboutIntroBlock', dz: 'CrossIconSfc', pz: 'renderCrossIcon', VM: 'CrossIcon',
  Lz: 'FooterBlockSfc', l0: 'FooterBlock', Pz: 'HeaderBlockSfc', WM: 'HeaderBlock', Jz: 'CardBlockSfc', Zz: 'CardBlock',
  rV: 'WebglSectionBlockSfc', YM: 'WebglSectionBlock', aV: 'AboutView', dV: 'ArrowButtonSfc', C_: 'ArrowButton',
  RV: 'ArchivesBlockSfc', BV: 'ArchivesBlock', UV: 'AgencyLinkSfc', rS: 'AgencyLink', YV: 'HomeHeroBlockSfc', XV: 'HomeHeroBlock',
  JV: 'HomeIntroBlockSfc', ZV: 'HomeIntroBlock', x4: 'ProjectBlockSfc', oS: 'ProjectBlock', w4: 'HomeViewSfc', b4: 'HomeView',
  EW: 'PlaygroundContentBlockSfc', SW: 'PlaygroundContentBlock', TW: 'PlaygroundHeroBlockSfc', CW: 'PlaygroundHeroBlock',
  IW: 'PlaygroundViewSfc', RW: 'PlaygroundView', QW: 'NavbarSfc', zW: 'NavbarComponent', h5: 'LoaderBlock',
  T5: 'VideoPlayerSfc', C5: 'VideoPlayer', L5: 'AppRootSfc', P5: 'AppRoot',
  Pf: 'previousRouteName', BW: 'ROUTE_NAMES', DW: 'homeUrl', Wu: 'router',
  VW: 'stripTrailingSlash', sI: 'SITE_URL', lS: 'SITE_NAME', WW: 'SITE_LOCALE', YW: 'THEME_COLOR', XW: 'TWITTER_SITE', qW: 'TWITTER_CREATOR',
  jW: 'AUTHOR', KW: 'PREVIEW_IMAGE_PATH', Mo: 'PREVIEW_IMAGE', JW: 'DEFAULT_DESCRIPTION', cS: 'SEO_PAGES', ZW: 'absoluteUrl',
  $W: 'seoForRoute', cn: 'setMeta', Hg: 'setLink', e5: 'applySeo', t5: 'useSeo', M5: 'hideAllBeeTexts',
  // app / tools
  o8: 'URL_PARAM_KEYS', a8: 'URLParams', l8: 'SoundController', c8: 'Mouse', u8: 'Viewport', h8: 'createTools',
  Pa: 'App', X_: 'AppClass', I: 'app', J6: 'preventBrowserZoom', Z6: 'injectWebManifestLink',
  // webgl
  f8: 'fullscreenCamera', x0: 'fullscreenTriangle', gA: 'sharedUniforms', Yl: 'TOP_LAYER',
  _8: 'shaderChunkId', bn: 'createShaderChunk',
  v8: 'noiseFragmentShader', FS: 'noiseFragmentChunk', y8: 'noiseVertexShader', NS: 'noiseVertexChunk', x8: 'NOISE_STRENGTH', E8: 'NoiseMaterial',
  S8: 'velocityBlendFragmentShader', w8: 'velocityBlendVertexShader', b8: 'VelocityBlendShader',
  T8: 'finalFragmentShader', C8: 'finalVertexShader', M8: 'FinalShader', I8: 'LayerRenderPass', kS: 'Renderer', R8: 'ScrollCamera',
  B8: 'colorFragmentShader', D8: 'colorFragmentChunk', L8: 'colorVertexShader', P8: 'colorVertexChunk', O8: 'ColorMaterial',
  F8: 'mediaFragmentShader', N8: 'mediaFragmentChunk', k8: 'mediaVertexShader', U8: 'mediaVertexChunk', G8: 'MediaMaterial',
  rY: 'MainScene', oY: 'MainCamera',
  aY: 'envFragmentShader', lY: 'envFragmentChunk', cY: 'envVertexShader', uY: 'envVertexChunk', FI: 'EnvTextureMaterial',
  hY: 'leavesFragmentShader', dY: 'leavesFragmentChunk', fY: 'leavesVertexShader', pY: 'leavesVertexChunk', AY: 'LeavesMaterial',
  gY: 'textureFragmentShader', mY: 'textureFragmentChunk', _Y: 'textureVertexShader', vY: 'textureVertexChunk', yY: 'TextureMaterial',
  xY: 'gradientFragmentShader', EY: 'gradientFragmentChunk', SY: 'gradientVertexShader', wY: 'gradientVertexChunk', bY: 'GradientMaterial', NI: 'GradientSphere',
  TY: 'cloudsFragmentShader', CY: 'cloudsFragmentChunk', MY: 'cloudsVertexShader', IY: 'cloudsVertexChunk', RY: 'CloudsMaterial',
  kI: 'MIN_FILTERS', UI: 'MAG_FILTERS', W_: 'WRAPPINGS', Rh: 'setLinearFilters', BY: 'TEXEL_MAX_CROSS_TEXTURES', E0: 'usesTexelMaxCross',
  GI: 'texelMaxCrossDefines', Qf: 'applyTextureDefaults', DY: 'textureResolution', HI: 'setMaterialTexture', qo: 'filterName',
  QI: 'textureSettings', zI: 'textureDebugParams', Zh: 'filterTextureEntries', S0: 'applyTextureDebugSettings', VI: 'applyTextureSettings', WI: 'applyTextureEntries',
  YI: 'Clouds', LY: 'Particles',
  PY: 'waterFragmentShader', OY: 'waterFragmentChunk', FY: 'waterVertexShader', NY: 'waterVertexChunk', kY: 'WaterMaterial', UY: 'Water',
  w0: 'DEFAULT_BLUR_RADIUS', GY: 'BLUR_RADIUS_BY_TEXTURE', HY: 'HASH_BLUR_TEXTURES', aa: 'usesHashBlur', XI: 'isDesktopBlur', Sp: 'blurRadiusForDevice',
  qI: 'blurRadiusFor', jI: 'hashBlurTextureNames', QY: 'filterEntriesByTarget', KI: 'applyBlurRadius', JI: 'applyHashBlurDebug', ZI: 'hashBlurDefines',
  zY: 'ABOUT_TOP_COLOR', VY: 'ABOUT_BOTTOM_COLOR', WY: 'AboutEnvironment',
  YY: 'particlesFragmentShaderAlt', XY: 'particlesFragmentShader', qY: 'particlesFragmentChunk', jY: 'particlesVertexShader', KY: 'particlesVertexChunk', JY: 'ParticlesMaterial',
  ZY: 'particlesSimpleVertexShader', $Y: 'ParticlesSimple',
  XS: 'HOME_CLOUDS_COUNT', eX: 'HOME_PARTICLES_A', tX: 'HOME_PARTICLES_B', nX: 'HomeEnvironment',
  iX: 'EnvScene', sX: 'EnvCamera', rX: 'CameraRig', oX: 'OrthoCamera', aX: 'TopCamera',
  CX: 'PAGE_TRANSITION_KEY', MX: 'coverScale', pm: 'OUTPUT_FRAGMENT_INCLUDE', Am: 'BEGIN_VERTEX_INCLUDE',
  IX: 'pageTransitionUniformsGlsl', RX: 'pageTransitionFragmentGlsl', gm: 'SHADOW_OUTPUT_LINE', BX: 'pageTransitionShadowFragmentGlsl',
  DX: 'pageTransitionShadowRevealGlsl', LX: 'revealScaleVertexGlsl', PX: 'injectRevealScale', OX: 'injectPageTransitionFragment',
  Pc: 'applyPageTransition', Sw: 'applyShadowPageTransition', ww: 'OUTGOING_LIGHT_LINE', bw: 'applyLitPageTransition',
  Tw: 'FRUIT_SCALE_A', mm: 'FRUIT_SCALE_B', FX: 'FRUIT_A', NX: 'FRUIT_B', kX: 'FRUIT_C', Cw: 'Fruits',
  C0: 'contentBeeTexts', Mw: 'BEE_IDLE_TEXTS', Iw: 'BEE_HOVER_TEXTS', _m: 'BEE_CONVERSATIONS', UX: 'BEE_TEXT_A', Rw: 'BEE_TEXT_B',
  GX: 'BEE_TEXT_C', HX: 'BEE_TEXT_D', QX: 'BEE_TEXT_E', zX: 'FRUIT_SOUND_2', VX: 'FRUIT_SOUND_1', i1: 'pickRandomExcept',
  WX: 'randomIdleText', YX: 'randomHoverText', XX: 'randomConversation',
  Bw: 'tmpVec3A', vm: 'tmpVec3B', ym: 'tmpBox3', qX: 'BEE_PROJ_A', jX: 'BEE_PROJ_B', KX: 'BEE_PROJ_C', JX: 'projectToScreen',
  ZX: 'beeTorsoMeshes', $X: 'screenBoundsOfMeshes', e6: 'beeScreenAnchor',
  Dw: 'BEE_A', Lw: 'BEE_B', Pw: 'BEE_C', t6: 'BEE_D', n6: 'BEE_E', i6: 'BEE_F', s6: 'BEE_G', r6: 'BEE_H', xm: 'BEE_I', o6: 'BEE_J', a6: 'BEE_K', Ow: 'BEE_L', l6: 'Bee',
  c6: 'loaderFragmentShader', u6: 'loaderFragmentChunk', h6: 'loaderVertexShader', d6: 'loaderVertexChunk', f6: 'LoaderMaterial', p6: 'LoaderPlane',
  A6: 'flowerBgFragmentShader', g6: 'flowerBgFragmentChunk', m6: 'flowerBgVertexShader', _6: 'flowerBgVertexChunk', v6: 'FlowerBackgroundMaterial',
  Fw: 'FLOWER_A', y6: 'FLOWER_PI', x6: 'FlowerGroup', Nw: 'TOP_SCENE_A', E6: 'TopScene',
  S6: 'FluidMouse', dc: 'fluidMouse', Qc: 'FluidShaderPass',
  kw: 'advectionFragmentShader', zc: 'fluidFaceVertexShader', w6: 'fluidLineVertexShader', b6: 'Advection',
  T6: 'divergenceFragmentShader', C6: 'Divergence', M6: 'externalForceFragmentShader', I6: 'externalForceVertexShader', R6: 'ExternalForce',
  B6: 'poissonFragmentShader', D6: 'Poisson', L6: 'pressureFragmentShader', P6: 'Pressure', O6: 'viscousFragmentShader', F6: 'Viscous',
  N6: 'FLUID_REFERENCE_WIDTH', Uw: 'FLUID_MIN_DT', k6: 'FLUID_MAX_DT', U6: 'FLUID_MAX_STEPS', G6: 'FluidSimulation',
  H6: 'velocityOutputFragmentShader', Q6: 'WebGL',
  // howler namespace
  Do: 'howler',
};
